### ISSUE TITLE
Moodle 3.2 - PHPUnit error 

### ISSUE THREAD

**Issue by aspark21** [moodleou/moodle-qtype_varnumeric#9]
Moodle: latest MOODLE_32_STABLE
Plugin: latest master
DB: both pgsql & mysqli

https://travis-ci.org/aspark21/moodle/jobs/211384020#L1728
1) qtype_varnumeric_statistics_from_steps_testcase::test_walkthrough_from_csv with data set #0 (array('00', 'deferredfeedback'), array(PHPUnit_Extensions_Database_DataSet_DefaultTable Object (...), PHPUnit_Extensions_Database_DataSet_DefaultTable Object (...)))
Argument 4 passed to quiz_statistics_report::get_all_stats_and_analysis() must be an instance of core\dml\sql_join, array given, called in /home/travis/build/aspark21/moodle/question/type/varnumeric/tests/stats_from_steps_walkthrough_test.php on line 79 and defined
/home/travis/build/aspark21/moodle/mod/quiz/report/statistics/report.php:609
/home/travis/build/aspark21/moodle/question/type/varnumeric/tests/stats_from_steps_walkthrough_test.php:79
/home/travis/build/aspark21/moodle/lib/phpunit/classes/advanced_testcase.php:80
To re-run:
 vendor/bin/phpunit qtype_varnumeric_statistics_from_steps_testcase question/type/varnumeric/tests/stats_from_steps_walkthrough_test.php

**Comment by timhunt** [comment]
Should be fixed in the latest version, which I just pushed.
